import { Job } from "@/types/job";

export const jobs: Job[] = [
  {
    id: "1",
    title: "Frontend Developer",
    company: "TechCorp",
    location: "Remote",
    type: "Full-time",
    description:
      "Join our growing frontend team to help build beautiful and performant user interfaces.",
    overview: "Build cutting-edge user interfaces with React",
    responsibilities: [
      "Develop and maintain responsive web applications using React.js",
      "Collaborate with design and backend teams",
      "Write clean, reusable, and maintainable code",
      "Optimize application for performance and scalability",
    ],
    techStack: ["React", "TypeScript", "Tailwind CSS", "Next.js"],
    dateOfJoining: "2025-06-15",
    salary: "$80,000 - $100,000",
  },
  {
    id: "2",
    title: "Backend Engineer",
    company: "DevSolutions",
    location: "New York, NY",
    type: "Part-time",
    description:
      "We are seeking a backend engineer with experience in scalable API development and database architecture.",
    overview: "Develop robust backend systems and APIs",
    responsibilities: [
      "Design, develop, and maintain RESTful APIs",
      "Manage PostgreSQL database schemas and migrations",
      "Implement authentication and authorization logic",
      "Collaborate with frontend engineers for integration",
    ],
    techStack: ["Node.js", "Express", "PostgreSQL", "Prisma", "Docker"],
    dateOfJoining: "2025-07-01",
    salary: "$50,000 - $70,000 (Part-time)",
  },
  {
    id: "3",
    title: "UI/UX Designer",
    company: "Creative Inc.",
    location: "San Francisco, CA",
    type: "Contract",
    description:
      "Looking for a creative UI/UX designer to design delightful and user-friendly web experiences.",
    overview: "Create intuitive and beautiful user experiences",
    responsibilities: [
      "Create wireframes, prototypes, and high-fidelity mockups",
      "Conduct user research and usability testing",
      "Collaborate closely with product and engineering teams",
      "Maintain and evolve the design system",
    ],
    techStack: ["Figma", "Adobe XD", "Miro", "HTML/CSS"],
    dateOfJoining: "2025-05-20",
    salary: "$5,000/month (Contract)",
  },
  {
    id: "4",
    title: "DevOps Engineer",
    company: "CloudTech",
    location: "Remote",
    type: "Full-time",
    description:
      "Seeking a DevOps engineer to build and maintain our cloud infrastructure and CI/CD pipelines.",
    overview: "Optimize and automate our cloud infrastructure",
    responsibilities: [
      "Design and implement CI/CD pipelines",
      "Manage AWS cloud infrastructure",
      "Implement monitoring and alerting systems",
      "Automate deployment and scaling processes",
    ],
    techStack: ["AWS", "Terraform", "Kubernetes", "Docker", "GitHub Actions"],
    dateOfJoining: "2025-06-01",
    salary: "$110,000 - $130,000",
  },
  {
    id: "5",
    title: "Data Scientist",
    company: "AnalyticsPro",
    location: "Boston, MA",
    type: "Full-time",
    description:
      "Join our data team to extract insights from large datasets and build predictive models.",
    overview: "Turn data into actionable business insights",
    responsibilities: [
      "Analyze complex datasets to identify trends",
      "Develop machine learning models",
      "Create data visualizations and reports",
      "Collaborate with product teams on data-driven features",
    ],
    techStack: ["Python", "Pandas", "TensorFlow", "SQL", "Tableau"],
    dateOfJoining: "2025-07-15",
    salary: "$90,000 - $120,000",
  },
  {
    id: "6",
    title: "Mobile Developer",
    company: "AppWorks",
    location: "Chicago, IL",
    type: "Full-time",
    description:
      "Looking for an experienced mobile developer to build cross-platform applications.",
    overview: "Build performant mobile apps for iOS and Android",
    responsibilities: [
      "Develop and maintain mobile applications",
      "Implement new features and UI components",
      "Optimize app performance and battery usage",
      "Work with backend teams on API integration",
    ],
    techStack: ["React Native", "TypeScript", "Swift", "Kotlin"],
    dateOfJoining: "2025-06-10",
    salary: "$85,000 - $105,000",
  },
  {
    id: "7",
    title: "Product Manager",
    company: "InnovateCo",
    location: "Austin, TX",
    type: "Full-time",
    description:
      "Lead product development from conception to launch, working with cross-functional teams.",
    overview: "Drive product vision and execution",
    responsibilities: [
      "Define product roadmap and strategy",
      "Gather and prioritize product requirements",
      "Coordinate between engineering, design, and marketing",
      "Analyze market trends and competition",
    ],
    techStack: ["JIRA", "Figma", "SQL", "Google Analytics"],
    dateOfJoining: "2025-08-01",
    salary: "$95,000 - $125,000",
  },
];
